title = 'SS Web Services'
baseURL = 'https://ssweb.services/'

[params]
    reviewLink = 'https://www.google.com/maps/place/SS+Web+Services/@36.9727211,-86.5023633,12z/data=!4m8!3m7!1s0x25cbf542c4ac53a7:0xb285fced4a3e4390!8m2!3d36.9727495!4d-86.4199629!9m1!1b1!16s%2Fg%2F11v03dq8wd?hl=en-US&entry=ttu'
    testLink = "https://www.google.com/maps/place/Anna's+Greek+Restaurant/@36.989784,-86.444706,17z/data=!4m8!3m7!1s0x8865e879ba064f2d:0x71efedd0254473df!8m2!3d36.989784!4d-86.444706!9m1!1b1!16s%2Fg%2F1tjs5p7j?hl=en-US&entry=ttu" 

summaryLength = 30

[markup]
    [markup.goldmark]
        [markup.goldmark.parser]
            wrapStandAloneImageWithinParagraph = false
    [markup.goldmark.renderer]
         unsafe = true
    [markup.highlight]
        style = "modus-vivendi"

[module]
    [[module.mounts]]
        source="static"
        target="static"
    [[module.mounts]]
        source="node_modules"
        target="static/node_modules"
    [[module.mounts]]
        source="favicon"
        target="static"
