title = 'SS Web Services'
baseURL = 'https://ssweb.services/'

summaryLength = 30

[markup]
    [markup.goldmark]
        [markup.goldmark.parser]
            wrapStandAloneImageWithinParagraph = false
    [markup.goldmark.renderer]
         unsafe = true
    [markup.highlight]
        style = "modus-vivendi"

[module]
    [[module.mounts]]
        source="static"
        target="static"
    [[module.mounts]]
        source="node_modules"
        target="static/node_modules"
